title: "MITRE ATT&CK Training Module for Forensic Analysts"
email: "your-email@example.com" # Optional
description: "A comprehensive training module for DFIR professionals leveraging the MITRE ATT&CK Framework."
baseurl: "" # If hosted at root of the repo
url: "https://5h1Vm.github.io" # Your GitHub Pages URL

author:
  name: "Kopal Chaturvedi"
  bio: "M.Sc. DFIS Student @ NFSU Delhi"
  location: "India"

logo: "/assets/images/nfsu-logo.png" # Optional logo placement
repository: "5h1Vm/mitre-module"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # enables dark mode skin (auto-detect possible)

# Plugins for GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

# Social (Optional)
social:
  github: 5h1Vm
  linkedin: 5h1Vm
  twitter: 5h1Vm
  instagram: 5h1Vm

