title: "MITRE ATT&CK Training Module for Forensic Analysts"
email: "kopal.dfis2242609@nfsu.ac.in"
description: "A comprehensive training module for DFIR professionals leveraging the MITRE ATT&CK Framework."
baseurl: "" 
url: "https://5h1vm.github.io/mitre-module/"

author:
  name: "Kopal Chaturvedi"
  bio: "M.Sc. DFIS Student @ NFSU Delhi"
  location: "India"

logo: "/assets/images/nfsu-logo.png"
repository: "5h1Vm/mitre-module"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default"  # Use light mode (change to default for light mode)

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

social:
  github: 5h1Vm
  linkedin: 5h1Vm
  twitter: 5h1Vm
  instagram: 5h1Vm
